apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ludivault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/kowalskipiotr98/ludivault-api:latest
          ports:
            - containerPort: 5500
          env:
            - name: LUDIVAULT_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_CONNECTION_STRING
            - name: GIN_MODE
              value: release

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ludivault
spec:
  ports:
    - port: 5500
      targetPort: 5500
  selector:
    app: api
