apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ludivault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: ludivault
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-17-storage
      volumes:
        - name: postgres-17-storage
          persistentVolumeClaim:
            claimName: postgres-17-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-17-pvc
  namespace: ludivault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: ludivault
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./pg-data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ludivault
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
