apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: ludivault
type: Opaque
data:
  POSTGRES_USER: bHVkaXZhdWx0
  POSTGRES_PASSWORD: bHVkaXZhdWx0
  POSTGRES_CONNECTION_STRING: aG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlIHVzZXI9bHVkaXZhdWx0IGRibmFtZT1sdWRpdmF1bHQgcGFzc3dvcmQ9bHVkaXZhdWx0IHNzbG1vZGU9ZGlzYWJsZQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: sso-data
  namespace: ludivault
type: Opaque
data:
  LUDIVAULT_SESSION_KEY: "<SET TO RANDOM STRING>"
  # You MUST fill at least one set of values, otherwise the app won't launch
  # Then you should add the selected config to api.yml and apply

  LUDIVAULT_SSO_GITEA_CLIENT_ID: ""
  LUDIVAULT_SSO_GITEA_CLIENT_SECRET: ""
  LUDIVAULT_SSO_GITEA_URL: ""

  LUDIVAULT_SSO_TWITCH_CLIENT_ID: ""
  LUDIVAULT_SSO_TWITCH_CLIENT_SECRET: ""

  LUDIVAULT_SSO_GITHUB_CLIENT_ID: ""
  LUDIVAULT_SSO_GITHUB_CLIENT_SECRET: ""

  LUDIVAULT_SSO_DISCORD_CLIENT_ID: ""
  LUDIVAULT_SSO_DISCORD_CLIENT_SECRET: ""

  LUDIVAULT_SSO_GOOGLE_CLIENT_ID: ""
  LUDIVAULT_SSO_GOOGLE_CLIENT_SECRET: ""

  LUDIVAULT_SSO_STEAM_CLIENT_SECRET: ""

  LUDIVAULT_SSO_OIDC_CLIENT_ID: ""
  LUDIVAULT_SSO_OIDC_CLIENT_SECRET: ""
  LUDIVAULT_SSO_OIDC_DISCOVERY_URL: ""
