apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: ludivault
type: Opaque
data:
  POSTGRES_USER: bHVkaXZhdWx0
  POSTGRES_PASSWORD: bHVkaXZhdWx0
  POSTGRES_CONNECTION_STRING: aG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlIHVzZXI9bHVkaXZhdWx0IGRibmFtZT1sdWRpdmF1bHQgcGFzc3dvcmQ9bHVkaXZhdWx0IHNzbG1vZGU9ZGlzYWJsZQ==
